#
# FURNACE Application Configuration File
#

# Application Name:
# This is the name of your application
app_name: Untitled Application

# Application URL:
# This is the full url to the application root (including http://)
app_url: http://example.org


# Database Engine:
#   Specifies which datasource to use when connecting. Note that,
#   at the moment, the only valid value is "MDB2".
db_engine: MDB2

# Debug Level:
#	2: Verbose output, benchmarks, debug info. 
# 	1: Error messages only, may still contain sensitive information
#      not suitable for a production environment.
#   0: No errors or warnings, suitable for a production environment.
debug_level: 1

#
# DATASOURCES
# Application datasources are divided at the top level among
# those that are for "debug"/development use, and those that 
# are for production use. If debug_level (above) is > 0, only the
# sources under "debug" will be available. The minimum requirement
# in this section is that a datasource called "default" be specified
# for each of "debug" and "production". Other, additional datasources
# in either section are optional. You can reference a specific datasource
# from the code by using the global database access function _db(). 
# If used with no parameters, _db() references the currently enabled "default"
# datasource (debug or production depending on debug_level). If given a 
# string, the function will attempt to return a connection to the datasource
# whose label matches the string (again, debug or production according to 
# debug_level). 
#
# Examples:
#
#   _db()->query(...) will query the "default" datasource
#   _db('analytics')->query(...) will query the "analytics" datasource
#
datasources:
  debug:
    default: "driver://user:pass@server/dbname"
  production:
    default: "driver://user:pass@server/dbname"


#
# Password Salt
# A password salt is a unique, hard to guess string that is 
# used in combination with user-selected passwords to provide
# additional security guarantees. 
# NOTE: For security, you should *change* this for each project
#
password_salt: "daFc893nv5ad7b4{3k%6Zx&3k00(Dz?34f%23/z4GGz"


# Application URL Base:
#   The base url (default is /) to expect at the beginning of 
#   each request. This is particularly helpful when your 
#   webapp does not reside at the site root (ie: in a sub-
#   directory like: http://example.com/apps/myapp). Always
#   include a trailing '/'.
url_base: /


# Application Root Password
#   Setting this password will allow you to manage your application
#   using the FUEL web-based management interface. If this password
#   is blank, you will not be able to use FUEL.
root_password: 


