<?php
/*
 * THIS FILE IS AUTOGENERATED! Edits made directly to this file will be lost.
 * Instead, modify the object-specific classes which can be found in
 * <application_root>/app/model/objects/* which extend the classes in this file.
 * 
 */
class ApplicationModel {
    
}
?>