#
# FURNACE Application Route Definition File
#
# Mappings between URLs and Controller/View pairs
# NOTE: Order is important! The Router runs top to bottom, 
# stopping after it has found a route that matches.
#
#
#
###########################################################
## ROUTES FOR EXTENSIONS
## Labels for extensions must begin with '_' and must at a minimum provide
##  a 'path' (name of the directory under /plugins/extensions)
##  a 'prefix' (the portion of the url to ignore for these routes)
##  a 'routes' (the array of defined routes for this extension)
##
_fuel:
  path:   org.frameworkers.fuel
  prefix: /fuel
  theme:  default
  routes:
    default:
      url: /:controller/:view
    default_index:
      url: /:controller
      map: { view: index }


###########################################################
## ADD CUSTOM ROUTES HERE:
## Add custom routes (if needed) for your application here.
##
login: 
  url: /login
  map: { controller: _default, view: login }
logout:
  url: /logout
  map: { controller: _default, view: logout }
forgotpass:
  url: /forgotpass
  map: { controller: _default, view: forgotpass }



###########################################################
## SITEWIDE DEFAULT ROUTES
## These routes ship with every furnace installation.
## Since they appear at the bottom of the file, they will
## only be matched if every previous rule fails. 
##
##
default:
  url: /:controller/:view
default_index:
  url: /:controller
  map: { view: index }